// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeShare.Persistence.DatabaseContext;

#nullable disable

namespace RecipeShare.Persistence.Migrations
{
    [DbContext(typeof(RecipeDatabaseContext))]
    [Migration("20250610152808_FixDynamicValuesInHasData")]
    partial class FixDynamicValuesInHasData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeShare.Domain.DietaryTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DietaryTags");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "Keto"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vegan"
                        });
                });

            modelBuilder.Entity("RecipeShare.Domain.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CookingTime")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookingTime = 30,
                            CreatedBy = "Gordon Ramsey",
                            DateCreated = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ingredients = "Tomatoes, Basil, Olive Oil, Garlic, Salt, Pepper",
                            ModifiedBy = "Jamie Oliver",
                            Steps = "1. Preheat oven to 200C. 2. Chop tomatoes and garlic. 3. Mix with olive oil, salt, and pepper. 4. Roast for 20 minutes. 5. Serve with fresh basil.",
                            Title = "The Delicious Recipes of Jamie Oliver"
                        });
                });

            modelBuilder.Entity("RecipeShare.Domain.RecipeDietaryTag", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("DietaryTagId")
                        .HasColumnType("int");

                    b.HasKey("RecipeId", "DietaryTagId");

                    b.HasIndex("DietaryTagId");

                    b.ToTable("RecipeDietaryTags");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            DietaryTagId = 2
                        },
                        new
                        {
                            RecipeId = 1,
                            DietaryTagId = 3
                        });
                });

            modelBuilder.Entity("RecipeShare.Domain.RecipeDietaryTag", b =>
                {
                    b.HasOne("RecipeShare.Domain.DietaryTag", "DietaryTag")
                        .WithMany("RecipeDietaryTags")
                        .HasForeignKey("DietaryTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeShare.Domain.Recipe", "Recipe")
                        .WithMany("RecipeDietaryTags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietaryTag");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeShare.Domain.DietaryTag", b =>
                {
                    b.Navigation("RecipeDietaryTags");
                });

            modelBuilder.Entity("RecipeShare.Domain.Recipe", b =>
                {
                    b.Navigation("RecipeDietaryTags");
                });
#pragma warning restore 612, 618
        }
    }
}
